# Generated by Django 4.0.1 on 2022-01-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('HospitalID', models.BigIntegerField(max_length=32, primary_key=True, serialize=False)),
                ('HospitalName', models.CharField(max_length=32)),
                ('HospitalRating', models.FloatField(default=0)),
                ('DoctorNum', models.IntegerField(default=0)),
                ('HospitalAddress', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.BigIntegerField(max_length=32, primary_key=True, serialize=False)),
                ('PCrawlDate', models.DateTimeField(blank=True, null=True)),
                ('ProductName', models.CharField(max_length=32)),
                ('ProductOPrice', models.FloatField(default=0)),
                ('ProductPrice', models.FloatField(default=0)),
                ('ProductSale', models.IntegerField(default=0)),
                ('ReturnRatio', models.FloatField(default=0)),
                ('ProductAPrice', models.FloatField(default=0)),
                ('PReviewNum', models.IntegerField(default=0)),
                ('PPostReviewNum', models.IntegerField(default=0)),
                ('PNegReviewNum', models.IntegerField(default=0)),
                ('PAddReviewNum', models.IntegerField(default=0)),
                ('PImageReviewNum', models.IntegerField(default=0)),
                ('PVideoReviewNum', models.IntegerField(default=0)),
                ('PFirstCommentTime', models.DateTimeField()),
                ('PAverageScore', models.FloatField(default=0)),
                ('HospitalID', models.ForeignKey(db_column='HospitalID', on_delete=django.db.models.deletion.DO_NOTHING, to='grab.hospital')),
            ],
        ),
    ]
