# Generated by Django 4.0.1 on 2022-01-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(max_length=128),
        ),
    ]
