# Generated by Django 4.0.1 on 2022-01-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0002_alter_product_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PFirstCommentTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
