# Generated by Django 4.0.1 on 2022-01-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0003_alter_product_pfirstcommenttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('ReviewerID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ReviewerName', models.CharField(max_length=32)),
                ('ReviewerAge', models.IntegerField(default=0)),
                ('ReviewerGender', models.CharField(blank=True, max_length=1, null=True)),
                ('ReviewerCity', models.CharField(max_length=32)),
                ('ReviewerPosts', models.IntegerField(default=0)),
                ('ReviewerFollwer', models.IntegerField(default=0)),
                ('ReviewerLikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='APatentNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='CrawlTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HAddReviewNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HHQReviewNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HImageReviewNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HNegReviewNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HPostReviewNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HReviewNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HVideoReviewNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HospitalCity',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HospitalFollower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HospitalSRating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HospitalTRating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HospitalType',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HospitalURating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='MGCNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ProjectNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='RecodeYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ReputNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Reputation',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ReviewNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ServiceNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='HospitalID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('ReviewID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('RCrawlDate', models.DateTimeField(blank=True, null=True)),
                ('IsCustom1Review', models.BooleanField(blank=True, null=True)),
                ('IsCustom2Review', models.BooleanField(blank=True, null=True)),
                ('IsHQReview', models.BooleanField(blank=True, null=True)),
                ('IsEOReview', models.BooleanField(blank=True, null=True)),
                ('IsImageReview', models.BooleanField(blank=True, null=True)),
                ('IsVideoReview', models.BooleanField(blank=True, null=True)),
                ('ReviewDate', models.DateTimeField()),
                ('ReviewViews', models.IntegerField(default=0)),
                ('ReviewRating', models.FloatField(default=0)),
                ('ReviewERating', models.FloatField(default=0)),
                ('ReviewSRating', models.FloatField(default=0)),
                ('ReviewTRating', models.FloatField(default=0)),
                ('ReviewPRating', models.FloatField(default=0)),
                ('ReviewImageNum', models.IntegerField(default=0)),
                ('ReviewContent', models.TextField(default='')),
                ('ReviewTextLen', models.IntegerField(default=0)),
                ('ReviewLikeNum', models.IntegerField(default=0)),
                ('ReviewFollowNum', models.IntegerField(default=0)),
                ('ReviewReplyNum', models.IntegerField(default=0)),
                ('ReviewerID', models.ForeignKey(db_column='ReviewerID', on_delete=django.db.models.deletion.DO_NOTHING, to='grab.reviewer')),
            ],
        ),
    ]
