# Generated by Django 4.0.1 on 2022-01-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0004_reviewer_hospital_apatentnum_hospital_crawltime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='HospitalName',
            field=models.CharField(max_length=64),
        ),
    ]
