# Generated by Django 4.0.1 on 2022-01-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0005_alter_hospital_hospitalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='RecodeYear',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
