# Generated by Django 4.0.1 on 2022-01-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0007_reviewer_reviewerexp_reviewer_reviewerfollowee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='ReviewImage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='diary',
            name='ReviewVideo',
            field=models.TextField(default=''),
        ),
    ]
