# Generated by Django 4.0.1 on 2022-01-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0008_diary_reviewimage_diary_reviewvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='FollowReviewNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='ReviewAddText',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
