# Generated by Django 4.0.1 on 2022-01-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0009_diary_followreviewnum_diary_reviewaddtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='ParentId',
            field=models.ForeignKey(blank=True, db_column='ParentId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grab.diary'),
        ),
    ]
