# Generated by Django 4.0.1 on 2022-01-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0010_diary_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='ReviewerID',
            field=models.ForeignKey(blank=True, db_column='ReviewerID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grab.reviewer'),
        ),
    ]
