# Generated by Django 4.0.1 on 2022-01-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0011_alter_diary_reviewerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='UserTyle',
            field=models.CharField(default='用户', max_length=2),
        ),
    ]
