# Generated by Django 4.0.1 on 2022-01-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0013_rename_usertyle_reviewer_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='VoicePrice',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='doctor',
            name='VoiceService',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='TextPrice',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='VideoPrice',
            field=models.CharField(default='', max_length=32),
        ),
    ]
